#!/usr/bin/env python3
"""Centralized user-visible texts for GUI."""

from __future__ import annotations

APP_TITLE = "网易云音乐下载助手"
APP_DESC = "输入网易云音乐歌曲链接后点击检测（支持长链、短链与分享文案）。"
STATUS_IDLE = "状态：待输入"
STATUS_DETECTING = "状态：检测中..."
STATUS_DETECT_DONE = "状态：检测完成"
STATUS_DETECT_FAILED = "状态：检测失败"
STATUS_DOWNLOADING = "状态：下载中..."
STATUS_DOWNLOAD_NOT_DONE = "状态：下载未完成"
STATUS_LOGOUT = "状态：已退出登录"
STATUS_LOGIN_UPDATED = "状态：登录已更新，可继续检测。"
STATUS_CANCELING = "正在取消..."

LOGIN_DIALOG_TITLE = "网易云音乐登录"
LOGIN_INFO = "请在下方页面完成网易云音乐扫码登录，登录成功后点击“确认并继续”。"
LOGIN_REMEMBER = "记住登录状态（下次启动自动检测）"
LOGIN_WEB_GROUP = "扫码登录"
LOGIN_WEB_HINT = "提示：若默认不是扫码页，请点击“扫码登录”。完成登录后点击下方确认按钮。"
LOGIN_FALLBACK_HINT = "当前环境未安装 Qt WebEngine，无法打开内嵌登录页。请安装后重试。"
LOGIN_BTN_CONFIRM = "确认并继续"
BTN_CANCEL = "取消"
BTN_CLOSE = "关闭"
BTN_DOWNLOAD = "下载"
BTN_START_DOWNLOAD = "开始下载"

ACCOUNT_LABEL_NICKNAME_LOGOUT = "昵称：未登录"
ACCOUNT_LABEL_VIP_UNKNOWN = "会员：-"
ACCOUNT_LABEL_VIP = "会员：VIP"
ACCOUNT_LABEL_NORMAL = "会员：普通用户"
ACCOUNT_BTN_FALLBACK = "账户"
ACCOUNT_MENU_SWITCH = "切换账号"
ACCOUNT_MENU_LOGOUT = "退出当前账号"

BTN_DOWNLOAD_MANAGER = "下载管理"
BTN_DEPENDENCY_MANAGER = "依赖管理"
BTN_DETECT = "检测"
INPUT_PLACEHOLDER = "粘贴网易云歌曲链接（支持长链/短链/分享文案）"
URL_HELP_LABEL = "示例长链：{url}"
URL_HELP_TOOLTIP = "支持粘贴整段分享文案，程序会自动提取其中的歌曲链接。"

TITLE_WARNING = "提示"
TITLE_PARAM_ERROR = "参数错误"
TITLE_LOGIN_FAIL = "登录失败"
TITLE_LOGIN_EXPIRED = "登录过期"
TITLE_NETWORK_CHECK_FAIL = "网络校验失败"
TITLE_NOT_LOGIN = "未登录"
TITLE_SWITCH_CANCELED = "未切换账号"
TITLE_AVATAR_FAIL = "头像加载失败"
TITLE_LOGOUT = "退出账号"
TITLE_DETECT_FAIL = "检测失败"
TITLE_DOWNLOAD_FAIL = "下载失败"
TITLE_DOWNLOAD_DONE = "下载完成"
TITLE_DOWNLOAD_CANCELED = "已取消"
TITLE_DELETE_CONFIRM = "确认删除"
TITLE_PATH_MISSING = "路径不存在"
TITLE_DELETE_FAIL = "删除失败"
TITLE_PATH_ERROR = "路径错误"
TITLE_LOGIN_INVALID = "登录失效"
TITLE_DEP_MISSING = "依赖缺失"

MSG_NEED_LOGIN_ANY = "当前未登录任何账号，请登录任一网易云音乐账号"
MSG_NO_LOGIN_ON_START = "未登录网易云账号，无法正常使用，请登录账号"
MSG_SWITCH_CANCELED = "未切换账号，仍使用当前登录状态"
MSG_AVATAR_LOAD_FAILED = "账号头像加载失败，已使用默认头像"
MSG_LOGIN_COOKIE_MISSING = "未检测到登录凭证。请先完成扫码登录后再继续。"
MSG_LOGIN_INVALID = "登录态无效或已过期，请重新登录。"
MSG_LOGIN_REQUIRES_WEBENGINE = "当前环境缺少 Qt WebEngine，无法完成登录。请先执行：python3 -m pip install PySide6-Addons"
MSG_FFMPEG_NEED_INSTALL = "未检测到 ffmpeg，当前仅支持 MP3 下载。安装后可开启其他格式。"
MSG_FFMPEG_CONFIRM_MP3 = "未检测到 ffmpeg，将保持默认 MP3 格式下载。\n点击“是”继续进入下载设置，点击“否”取消本次下载。"
MSG_FFMPEG_INSTALL_GUIDE = "安装建议：macOS 执行 `brew install ffmpeg`；Windows 执行 `winget install Gyan.FFmpeg`。"
MSG_NEED_INPUT_URL = "请先输入歌曲链接或歌曲 ID。"
MSG_NEED_PICK_DIR = "请选择有效的下载目录。"
MSG_EMPTY_FILENAME = "文件名不能为空。"
MSG_DOWNLOAD_CANCELED = "下载已取消。"
MSG_LOGOUT_CONFIRM = "确定退出当前登录账号吗？"
MSG_NOT_LOGGED_IN = "当前未登录。"
MSG_NOT_SELECTED_RECORD = "请先选择一条下载记录。"
MSG_DOWNLOADS_EMPTY = "暂无下载记录"
MSG_UNSUPPORTED_FORMAT = "不支持的格式：{fmt}"
MSG_UNKNOWN = "未知"

DOWNLOAD_OPTIONS_TITLE = "下载设置"
DOWNLOAD_OPTIONS_DIR = "保存目录"
DOWNLOAD_OPTIONS_NAME = "文件名（不含后缀）"
DOWNLOAD_OPTIONS_FORMAT = "下载格式"
DOWNLOAD_OPTIONS_PREVIEW = "预估输出：{path}"
DOWNLOAD_DIR_PICKER_TITLE = "选择下载目录"
DOWNLOAD_DIR_PICKER_BTN = "选择..."

DOWNLOAD_PROGRESS_TITLE = "下载中"
DOWNLOAD_PROGRESS_INIT = "准备下载..."
DOWNLOAD_PROGRESS_SPEED = "速度：-"
DOWNLOAD_PROGRESS_PATH = "输出路径："
DOWNLOAD_PROGRESS_CANCEL = "取消下载"
DOWNLOAD_PROGRESS_DONE_BODY = "文件：{name}\n大小：{size}\n路径：{path}"
DOWNLOAD_PROGRESS_DONE_FALLBACK_NOTE = "\n提示：未安装 ffmpeg，已按源格式保存。"
DOWNLOAD_PROGRESS_TEXT_SIMPLE = "已下载 {downloaded}"
DOWNLOAD_PROGRESS_TEXT_FULL = "已下载 {downloaded} / {total}"

SONG_CONFIRM_TITLE = "歌曲检测结果"
SONG_CONFIRM_ID = "歌曲 ID"
SONG_CONFIRM_NAME = "歌名"
SONG_CONFIRM_DURATION = "时长"
SONG_CONFIRM_STATUS = "状态"
SONG_CONFIRM_REASON = "原因"
SONG_CONFIRM_CAN_DOWNLOAD = "可下载"
SONG_CONFIRM_CANT_DOWNLOAD = "不可下载"

MANAGER_TITLE = "下载管理"
MANAGER_COL_SONG = "歌曲"
MANAGER_COL_FILENAME = "文件名"
MANAGER_COL_SIZE = "大小"
MANAGER_COL_TIME = "下载时间"
MANAGER_COL_PATH = "路径"
MANAGER_BTN_OPEN_FOLDER = "打开文件夹"
MANAGER_BTN_DELETE_FILE = "删除文件"
MANAGER_BTN_REFRESH = "刷新"
MANAGER_MISSING_FOLDER = "目录不存在：{folder}"
MANAGER_DELETE_CONFIRM = "确定删除文件并移除记录吗？\n{path}"
DEPENDENCY_HINT_LIMITED = "部分功能受限"
DEPENDENCY_HINT_LIMITED_TIP = "检测到依赖缺失。点击“依赖管理”查看详情与安装方法。"
DEP_MANAGER_TITLE = "依赖管理"
DEP_MANAGER_DESC = "查看关键依赖状态。依赖缺失会导致部分功能受限。"
DEP_MANAGER_COL_NAME = "依赖"
DEP_MANAGER_COL_STATUS = "状态"
DEP_MANAGER_COL_IMPACT = "功能影响"
DEP_MANAGER_COL_INSTALL = "安装方法"
DEP_MANAGER_ITEM_FFMPEG = "ffmpeg"
DEP_MANAGER_STATUS_OK = "已安装"
DEP_MANAGER_STATUS_MISSING = "未安装"
DEP_MANAGER_IMPACT_OK = "支持所有下载格式与转码能力。"
DEP_MANAGER_IMPACT_MISSING = "仅支持 MP3 下载，其他格式转码不可用。"
DEP_MANAGER_INSTALL_OK = "-"
DEP_MANAGER_INSTALL_FFMPEG = "macOS: brew install ffmpeg\nWindows: winget install Gyan.FFmpeg"


def code_message(code: str, message: str) -> str:
    return f"{code}: {message}"


def login_network_confirm(code: str) -> str:
    return f"登录状态在线校验失败：{code}\n是否仍然继续？"


def detect_auth_expired(code: str, message: str) -> str:
    return f"{code}: {message}\n请点击头像菜单切换账号。"


def status_download_done(filename: str) -> str:
    return f"状态：下载完成 -> {filename}"


def speed_text(speed: str) -> str:
    return f"速度：{speed}/s"


def nickname_text(name: str) -> str:
    return f"昵称：{name}"
